AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Observability Lab - Simulated API Logs

Globals:
  Api:
    TracingEnabled: true

Resources:
  LogLevelFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: logs.lambda_handler
      Runtime: python3.14
      CodeUri: ./src
      Tracing: Active
      Events:
        LogLevelApi:
          Type: Api
          Properties:
            Path: /log/{level}
            Method: get

Outputs:
  PublicApiUrl:
    Description: "The live URL for your API Gateway"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/log"

